console.log("============================");
console.log("     McDONALD'S RECEIPT     ");
console.log("----------------------------");
console.log("        Order Details       ");
console.log("----------------------------");
console.log("Item       Quality   Price"  );
console.log("----------------------------");
console.log("🍔Burger      1      2.99"  );
console.log("🍟Fries       1      2.49"  );
console.log("🥤Soda        1      1.99"  );
console.log("----------------------------");
console.log("Total                 7.47  ");
console.log("============================");
